language: python
sudo: required
dist: xenial

python:
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip

install:
  - sudo apt-get install libturbojpeg python3-tk
  - bash ./tensorflow_toolkit/init_venv.sh

jobs:
  include:
    - stage: Code linting
      script:
        - . tensorflow_toolkit/venv/bin/activate
        - find ./tensorflow_toolkit -type f -name "*.py" -not -path "*/venv/*" ! -name "config*.py" -exec pylint --rcfile devtools/pylint.rc {} +
    - stage: Integration tests
      script:
        - . tensorflow_toolkit/venv/bin/activate
        - cd tensorflow_toolkit
        - nosetests
