language: python
sudo: required
dist: xenial

python:
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip

install:
  - sudo apt-get install libturbojpeg python3-tk
  - bash tools/init_venv.sh

jobs:
  include:
    - stage: Code linting
      script:
        - . venv/bin/activate
        - find ./training_toolbox -type f -name "*.py" ! -name "config*.py" -exec pylint --rcfile devtools/pylint.rc {} +
    - stage: Integration tests
      script:
        - . venv/bin/activate
        - cd training_toolbox
        - nosetests
